/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ModelRouteImport } from './routes/model'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiFactCheckRouteImport } from './routes/api/fact-check'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as ApiAnalyzeImageRouteImport } from './routes/api/analyze.image'
import { Route as ApiAnalyzeTextRouteImport } from './routes/api/analyze.text'
import { Route as ApiHistoryIdRouteImport } from './routes/api/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFactCheckRoute = ApiFactCheckRouteImport.update({
  id: '/api/fact-check',
  path: '/api/fact-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeImageRoute = ApiAnalyzeImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiAnalyzeRoute,
} as any)
const ApiAnalyzeTextRoute = ApiAnalyzeTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ApiAnalyzeRoute,
} as any)
const ApiHistoryIdRoute = ApiHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/model': typeof ModelRoute
  '/api/analyze': typeof ApiAnalyzeRouteWithChildren
  '/api/fact-check': typeof ApiFactCheckRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/result/$id': typeof ResultIdRoute
  '/api/analyze/image': typeof ApiAnalyzeImageRoute
  '/api/analyze/text': typeof ApiAnalyzeTextRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/model': typeof ModelRoute
  '/api/analyze': typeof ApiAnalyzeRouteWithChildren
  '/api/fact-check': typeof ApiFactCheckRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/result/$id': typeof ResultIdRoute
  '/api/analyze/image': typeof ApiAnalyzeImageRoute
  '/api/analyze/text': typeof ApiAnalyzeTextRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/model': typeof ModelRoute
  '/api/analyze': typeof ApiAnalyzeRouteWithChildren
  '/api/fact-check': typeof ApiFactCheckRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/result/$id': typeof ResultIdRoute
  '/api/analyze/image': typeof ApiAnalyzeImageRoute
  '/api/analyze/text': typeof ApiAnalyzeTextRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyze'
    | '/dashboard'
    | '/history'
    | '/how-it-works'
    | '/model'
    | '/api/analyze'
    | '/api/fact-check'
    | '/api/health'
    | '/api/history'
    | '/api/stats'
    | '/result/$id'
    | '/api/analyze/image'
    | '/api/analyze/text'
    | '/api/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze'
    | '/dashboard'
    | '/history'
    | '/how-it-works'
    | '/model'
    | '/api/analyze'
    | '/api/fact-check'
    | '/api/health'
    | '/api/history'
    | '/api/stats'
    | '/result/$id'
    | '/api/analyze/image'
    | '/api/analyze/text'
    | '/api/history/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyze'
    | '/dashboard'
    | '/history'
    | '/how-it-works'
    | '/model'
    | '/api/analyze'
    | '/api/fact-check'
    | '/api/health'
    | '/api/history'
    | '/api/stats'
    | '/result/$id'
    | '/api/analyze/image'
    | '/api/analyze/text'
    | '/api/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzeRoute: typeof AnalyzeRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ModelRoute: typeof ModelRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRouteWithChildren
  ApiFactCheckRoute: typeof ApiFactCheckRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ApiStatsRoute: typeof ApiStatsRoute
  ResultIdRoute: typeof ResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fact-check': {
      id: '/api/fact-check'
      path: '/api/fact-check'
      fullPath: '/api/fact-check'
      preLoaderRoute: typeof ApiFactCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/image': {
      id: '/api/analyze/image'
      path: '/image'
      fullPath: '/api/analyze/image'
      preLoaderRoute: typeof ApiAnalyzeImageRouteImport
      parentRoute: typeof ApiAnalyzeRoute
    }
    '/api/analyze/text': {
      id: '/api/analyze/text'
      path: '/text'
      fullPath: '/api/analyze/text'
      preLoaderRoute: typeof ApiAnalyzeTextRouteImport
      parentRoute: typeof ApiAnalyzeRoute
    }
    '/api/history/$id': {
      id: '/api/history/$id'
      path: '/$id'
      fullPath: '/api/history/$id'
      preLoaderRoute: typeof ApiHistoryIdRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
  }
}

interface ApiAnalyzeRouteChildren {
  ApiAnalyzeImageRoute: typeof ApiAnalyzeImageRoute
  ApiAnalyzeTextRoute: typeof ApiAnalyzeTextRoute
}

const ApiAnalyzeRouteChildren: ApiAnalyzeRouteChildren = {
  ApiAnalyzeImageRoute: ApiAnalyzeImageRoute,
  ApiAnalyzeTextRoute: ApiAnalyzeTextRoute,
}

const ApiAnalyzeRouteWithChildren = ApiAnalyzeRoute._addFileChildren(
  ApiAnalyzeRouteChildren,
)

interface ApiHistoryRouteChildren {
  ApiHistoryIdRoute: typeof ApiHistoryIdRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistoryIdRoute: ApiHistoryIdRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzeRoute: AnalyzeRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  HowItWorksRoute: HowItWorksRoute,
  ModelRoute: ModelRoute,
  ApiAnalyzeRoute: ApiAnalyzeRouteWithChildren,
  ApiFactCheckRoute: ApiFactCheckRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ApiStatsRoute: ApiStatsRoute,
  ResultIdRoute: ResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
